USE biblio_3
SELECT * FROM Alumno
INSERT INTO Alumno VALUES('Daniel',1234533,'1','Ovalle','Hernandez','s',33,'M');
INSERT INTO Alumno VALUES('Uziel',12235533,'1','Pueñuela','Rodriguez','s',22,'M');
INSERT INTO Alumno VALUES('Aaron',1234567,'6','Olivo','Alvarez','s',18,'M');
INSERT INTO Alumno VALUES('Juan',1305920,'5','Jacobo','Acuña','s',17,'M');
INSERT INTO Alumno VALUES('Andres',75301264,'4','Carbajal','Ramos','s',21,'M');
INSERT INTO Alumno VALUES('Carlos',0134572,'4','Rodriguez','Guitierrez','n',20,'M');
INSERT INTO Alumno VALUES('Hugo',2136548,'6','Martinez','Raimrez','s',17,'M');
INSERT INTO Alumno VALUES('Fransisco',0214872,'2','Aguirre','Mendoza','n',20,'M');
INSERT INTO Alumno VALUES('Elias',12365948,'1','Huerta','Pacheco','s',21,'M');
INSERT INTO Alumno VALUES('Luis',17349658,'3','Hernandez','Rodriguez','s',22,'M');
INSERT INTO Alumno VALUES('Enrique',1732564,'5','Peña','Treviño','s',20,'M');
INSERT INTO Alumno VALUES('Jose',1732365,'4','Venegas','Barrera','s',19,'M');
INSERT INTO Alumno VALUES('Marcelo',1645780,'3','Gamboa','Santana','s',19,'M');
INSERT INTO Alumno VALUES('Ivan',1624597,'5','Gomez','Beinitez','s',20,'M');
INSERT INTO Alumno VALUES('Bruce',1796548,'3','Araujo','hernandez','s',25,'M');
INSERT INTO Alumno VALUES('Juana',1754962,'1','Aguilar','Alanis','n',18,'F');
INSERT INTO Alumno VALUES('Abril',1745823,'2','Campos','Picasso','s',18,'F');
INSERT INTO Alumno VALUES('Andrea',1789453,'3','Rivera','Perez','s',17,'F');
INSERT INTO Alumno VALUES('Carolina',1738546,'4','de Leon','Villareal','s',17,'F');
INSERT INTO Alumno VALUES('Karen',1794652,'5','Rojas','de Luna','n',19,'F');
INSERT INTO Alumno VALUES('Ana',1723465,'6','Moreno','Martinez','s',20,'F');
INSERT INTO Alumno VALUES('Paola',1785246,'3','Cardenas','Calderon','s',20,'F');
INSERT INTO Alumno VALUES('Hanzel',1799652,'1','Baldemar','Mata','s',17,'F');
INSERT INTO Alumno VALUES('Mariana',1712034,'2','Carranza','Zuñiga','s',20,'F');
INSERT INTO Alumno VALUES('Marisol',1745023,'4','Valdez','Falcon','s',21,'F');

SELECT * FROM Carrera
INSERT INTO cARRERA VALUES ('LSTI');
INSERT INTO Carrera VALUES ('LCC');
INSERT INTO Carrera VALUES ('LA');
INSERT INTO Carrera VALUES ('LF');
INSERT INTO Carrera VALUES ('LMAD');
INSERT INTO Carrera VALUES ('LM');

select *from Autor
insert into Autor values('Gabriel Garcia Marquez',' ');
insert into Autor values('Carlos Sisi',' ');
insert into Autor values('Dan Brown',' ');
insert into Autor values('J.K. Rowlin','Gabriel Garcia Marquez');
insert into Autor values('Lawrence',' ');
insert into Autor values('Daniel Goleman',' ');
insert into Autor values('Stephen King',' ');
insert into Autor values('Megan Maxwell','Jose Carlos');
insert into Autor values('Joseph Conrad',' ');
insert into Autor values('Jonh Grisham',' ');
insert into Autor values('Herman Melville',' ');
insert into Autor values('Johann Wolfgang von Goethe',' ');
insert into Autor values('Nikolai Gogol',' ');
insert into Autor values('Pablo Neruda',' ');
insert into Autor values('Juan Carlos Onetti.',' ');
insert into Autor values('Mario Vargas Llosa',' ');
insert into Autor values('Isabel Allende',' ');
insert into Autor values('Julio Cortázar',' ');
insert into Autor values('Jorge Luis Borges',' ');
insert into Autor values('Xavier Velasco','José Emilio Pacheco');
insert into Autor values('Carlos Fuentes',' ');
insert into Autor values('Juan Rulfo',' ');
insert into Autor values('Octavio Paz',' ');
insert into Autor values(' ','Stephen King');
insert into Autor values('Arturo Venegas',' ');
insert into Autor values('Ricardo Rogia',' ');
insert into Autor values('Uziel Peñuela',' ');
insert into Autor values('Wilson P.J.',' ');
insert into Autor values('Sam tech ',' ');
insert into Autor values('John Green ',' ');
insert into Autor values('Blue Jeans',' ');

select * from Editorial
insert into Editorial values ('Ariel');
insert into Editorial values ('Alianza');
insert into Editorial values ('Tecnos');
insert into Editorial values ('Sintesis');
insert into Editorial values ('Civitas');
insert into Editorial values ('Siglo XXI');
insert into Editorial values ('Tirant lo Blanch');
insert into Editorial values ('Catedra');
insert into Editorial values ('Aranzadi');
insert into Editorial values ('CSIC');
insert into Editorial values ('Piramide');
insert into Editorial values ('Critica');
insert into Editorial values ('McGraw-Hill');
insert into Editorial values ('Trotta');
insert into Editorial values ('Paidos');
insert into Editorial values ('Bosch');
insert into Editorial values ('Marcial Pons');
insert into Editorial values ('Universidad de Granada');
insert into Editorial values ('Centro de Estudios Politicos');
insert into Editorial values ('Universidad de Barcelona');
insert into Editorial values ('Universidad de Salamanca');
insert into Editorial values ('Espasa');
insert into Editorial values ('Akal');
insert into Editorial values ('Cometa');
insert into Editorial values ('Oceanos');
insert into Editorial values ('Comares');
insert into Editorial values ('Arco Libros');
insert into Editorial values ('Grao');
insert into Editorial values ('Dykinson');
insert into Editorial values ('Centro de Investigaciones Sociologicas');
insert into Editorial values ('Universidad de Sevilla');
insert into Editorial values ('Univerdidad de Extremadura');
insert into Editorial values ('Primociones y Publicaciones Universitarias (PPU)');
insert into Editorial values ('Universidad Nacional de Educaion a Distancia');
insert into Editorial values ('Universidad Complutense de Madrid');
insert into Editorial values ('Ministerio de Trabajo');
insert into Editorial values ('Universidade de Santiago de Compostela');
insert into Editorial values ('Universitat de Valencia');
insert into Editorial values ('Gredos');
insert into Editorial values ('Ministerio de Hacienda');
insert into Editorial values ('Cambridge University Press');
insert into Editorial values ('Taurus');
insert into Editorial values ('Icaria');
insert into Editorial values ('Ministerio de Cultura');
insert into Editorial values ('Universidad de Alicante');
insert into Editorial values ('Biblioteca Nueva');
insert into Editorial values ('Anthropos');
insert into Editorial values ('Universidad de Oviedo');
insert into Editorial values ('Narcea');
insert into Editorial values ('Visor');


select * from Seccion
insert into Seccion values('Matematicas');
insert into Seccion values('Fisica');
insert into Seccion values('Ciensias sociales');
insert into Seccion values('Programacion en C');
insert into Seccion values('Programacion en C#');
insert into Seccion values('Programacion Web');
insert into Seccion values('Ethical Hacking');
insert into Seccion values('Literatura');
insert into Seccion values('Calculo Diferencial');
insert into Seccion values('Calculo Integral');
insert into Seccion values('Estadistica');
insert into Seccion values('poesia');
insert into Seccion values('Ciencias Naturales');
insert into Seccion values('Medio Ambiente');
insert into Seccion values('Lenguas Extranjeras');
insert into Seccion values('Guias de Asesoramiento');
insert into Seccion values('Arquitecturas Computacionales');
insert into Seccion values('Sistemas Operativos');
insert into Seccion values('Circuitos Digitales');
insert into Seccion values('Redes y Comunicaciones');
insert into Seccion values('Derechos Informaticos');
insert into Seccion values('Normatividad y Regulaciones');
insert into Seccion values('Derechos Morales');
insert into Seccion values('Metodologias y Controles de Accesos');
insert into Seccion	values ('Recreacion');
insert into Seccion values ('Materias de Formacion Universitaria');


